-- ================================================================
-- PawLink — Full Seed Data (Sri Lankan Context)
-- ================================================================

-- ================================================================
-- 1. USERS
-- ================================================================
INSERT IGNORE INTO users (name, email, password, role, phone, bio) VALUES
-- Admin
('PawLink Admin',        'admin@pawlink.com',         '$2a$12$K.sQpRtYwB9NPDJwOZWmqevIuTsvyl/hzQzpSvO3N5mBxy8h8FluC', 'admin',        '+94112345678', 'Platform administrator.'),
-- Persons
('Nimal Perera',         'nimal@pawlink.com',          '$2a$12$Nimal123HashXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'person',       '+94771234567', 'Animal lover from Colombo. Passionate about rescuing strays.'),
('Kumari Jayasinghe',    'kumari@pawlink.com',         '$2a$12$LFGIvP3wnvSFj4DB2wpnROu3EF3lUAHo3xxWE/Nxymx63rb28L.Ui', 'person',      '+94772345678', 'Cat foster parent based in Kandy.'),
('Suresh Fernando',      'suresh@pawlink.com',         '$2a$12$LFGIvP3wnvSFj4DB2wpnROu3EF3lUAHo3xxWE/Nxymx63rb28L.Ui', 'person',      '+94773456789', 'Dog trainer and animal welfare volunteer.'),
('Dilani Wickramasinghe','dilani@pawlink.com',         '$2a$12$LFGIvP3wnvSFj4DB2wpnROu3EF3lUAHo3xxWE/Nxymx63rb28L.Ui', 'person',      '+94774567890', 'Lives in Galle, rescues injured roadside animals.'),
('Ruwan Bandara',        'ruwan@pawlink.com',          '$2a$12$LFGIvP3wnvSFj4DB2wpnROu3EF3lUAHo3xxWE/Nxymx63rb28L.Ui', 'person',      '+94775678901', 'Retired veterinary nurse. Based in Negombo.'),
-- Organizations
('Happy Paws Rescue',    'shelter@pawlink.com',        '$2a$12$3Gm.idPBi8O9zefP5ta9v..fs59wjMlBcBehee5W4Op3kZLevk.xG', 'organization', '+94112233445', NULL),
('Animal Lovers Shelter','animalshelter@pawlink.com',  '$2a$12$3Gm.idPBi8O9zefP5ta9v..fs59wjMlBcBehee5W4Op3kZLevk.xG', 'organization', '+94812233445', NULL),
('Safe Haven Rescues',   'safehaven@pawlink.com',      '$2a$12$3Gm.idPBi8O9zefP5ta9v..fs59wjMlBcBehee5W4Op3kZLevk.xG', 'organization', '+94312233445', NULL),
('Paws & Claws Sanctuary','pawsandclaws@pawlink.com',  '$2a$12$3Gm.idPBi8O9zefP5ta9v..fs59wjMlBcBehee5W4Op3kZLevk.xG', 'organization', '+94312344556', NULL);

-- NOTE: Replace '$2a$12$Nimal123HashXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-- with the bcrypt hash of 'Nimal@123' generated by your auth service.
-- All other person passwords use the same hash as 'User@123'.
-- All organization passwords use the same hash as 'Shelter@123'.

-- ================================================================
-- 2. ORGANIZATIONS
-- ================================================================
INSERT IGNORE INTO organizations
    (user_id, name, description, contact_number, address, city, latitude, longitude,
     website, max_capacity, current_occupancy, status, verified, profile_complete)
SELECT id, 'Happy Paws Rescue Foundation',
    'A Colombo-based rescue organization caring for abandoned dogs and cats since 2010.',
    '+94112233445', '123 Duplication Road, Colombo 03', 'Colombo',
    6.9271, 79.8612, 'https://happypaws.lk', 50, 18, 'approved', 1, 1
FROM users WHERE email = 'shelter@pawlink.com';

INSERT IGNORE INTO organizations
    (user_id, name, description, contact_number, address, city, latitude, longitude,
     website, max_capacity, current_occupancy, status, verified, profile_complete)
SELECT id, 'Animal Lovers Shelter',
    'Kandy hill-country shelter focused on rehabilitating injured and malnourished animals.',
    '+94812233445', '45 Peradeniya Road, Kandy', 'Kandy',
    7.2906, 80.6337, 'https://animallovers.lk', 30, 11, 'approved', 1, 1
FROM users WHERE email = 'animalshelter@pawlink.com';

INSERT IGNORE INTO organizations
    (user_id, name, description, contact_number, address, city, latitude, longitude,
     website, max_capacity, current_occupancy, status, verified, profile_complete)
SELECT id, 'Safe Haven Rescues',
    'South Colombo rescue shelter operating along Galle Road since 2015.',
    '+94312233445', '88 Galle Road, Mount Lavinia', 'Mount Lavinia',
    6.8301, 79.8675, NULL, 40, 15, 'approved', 1, 1
FROM users WHERE email = 'safehaven@pawlink.com';

INSERT IGNORE INTO organizations
    (user_id, name, description, contact_number, address, city, latitude, longitude,
     website, max_capacity, current_occupancy, status, verified, profile_complete)
SELECT id, 'Paws & Claws Sanctuary',
    'Negombo-based sanctuary near the coast, caring for all types of animals.',
    '+94312344556', '12 Lewis Place, Negombo', 'Negombo',
    7.2089, 79.8351, 'https://pawsandclaws.lk', 60, 22, 'approved', 1, 1
FROM users WHERE email = 'pawsandclaws@pawlink.com';

INSERT IGNORE INTO organizations
    (user_id, name, description, contact_number, address, city, latitude, longitude,
     website, max_capacity, current_occupancy, status, verified, profile_complete)
SELECT id, 'Galle Animal Welfare Society',
    'Galle Fort area welfare society rescuing and rehoming stray animals since 2018.',
    '+94912344556', '5 Lighthouse Street, Galle Fort', 'Galle',
    6.0535, 80.2210, NULL, 35, 9, 'approved', 1, 1
FROM users WHERE email = 'safehaven@pawlink.com';

-- ================================================================
-- 3. ORGANIZATION ANIMAL TYPES
-- ================================================================
INSERT IGNORE INTO organization_animal_types (organization_id, animal_type)
SELECT o.id, t.animal_type
FROM organizations o
JOIN (
    SELECT 'Happy Paws Rescue Foundation' AS org_name, 'dog'    AS animal_type UNION ALL
    SELECT 'Happy Paws Rescue Foundation',              'cat'                   UNION ALL
    SELECT 'Animal Lovers Shelter',                     'dog'                   UNION ALL
    SELECT 'Animal Lovers Shelter',                     'cat'                   UNION ALL
    SELECT 'Animal Lovers Shelter',                     'bird'                  UNION ALL
    SELECT 'Safe Haven Rescues',                        'dog'                   UNION ALL
    SELECT 'Safe Haven Rescues',                        'rabbit'                UNION ALL
    SELECT 'Paws & Claws Sanctuary',                    'dog'                   UNION ALL
    SELECT 'Paws & Claws Sanctuary',                    'cat'                   UNION ALL
    SELECT 'Paws & Claws Sanctuary',                    'other'                 UNION ALL
    SELECT 'Galle Animal Welfare Society',              'dog'                   UNION ALL
    SELECT 'Galle Animal Welfare Society',              'cat'
) t ON o.name = t.org_name;

-- ================================================================
-- 4. ORGANIZATION DOCUMENTS
-- ================================================================
INSERT INTO organization_documents (organization_id, document_url, document_type)
SELECT o.id, d.document_url, d.document_type
FROM organizations o
JOIN (
    SELECT 'Happy Paws Rescue Foundation'  AS org_name, 'https://docs.pawlink.lk/happypaws/reg.pdf',    'Registration Certificate' UNION ALL
    SELECT 'Happy Paws Rescue Foundation',              'https://docs.pawlink.lk/happypaws/tax.pdf',    'Tax Exemption Letter'     UNION ALL
    SELECT 'Animal Lovers Shelter',                     'https://docs.pawlink.lk/animallovers/reg.pdf', 'Registration Certificate' UNION ALL
    SELECT 'Safe Haven Rescues',                        'https://docs.pawlink.lk/safehaven/reg.pdf',    'Registration Certificate' UNION ALL
    SELECT 'Paws & Claws Sanctuary',                    'https://docs.pawlink.lk/pawsclaws/reg.pdf',    'Registration Certificate' UNION ALL
    SELECT 'Galle Animal Welfare Society',              'https://docs.pawlink.lk/galle/reg.pdf',        'Registration Certificate'
) d ON o.name = d.org_name;

-- ================================================================
-- 5. ORGANIZATION GALLERY
-- ================================================================
INSERT INTO organization_gallery (organization_id, image_url, caption)
SELECT o.id, g.image_url, g.caption
FROM organizations o
JOIN (
    SELECT 'Happy Paws Rescue Foundation'  AS org_name, 'https://gallery.pawlink.lk/happypaws/1.jpg',     'Our main kennels in Colombo 03'          UNION ALL
    SELECT 'Happy Paws Rescue Foundation',              'https://gallery.pawlink.lk/happypaws/2.jpg',     'Adoption day — March 2024'                UNION ALL
    SELECT 'Animal Lovers Shelter',                     'https://gallery.pawlink.lk/animallovers/1.jpg',  'Cat recovery ward — Kandy'                UNION ALL
    SELECT 'Animal Lovers Shelter',                     'https://gallery.pawlink.lk/animallovers/2.jpg',  'Volunteer feeding session'                UNION ALL
    SELECT 'Safe Haven Rescues',                        'https://gallery.pawlink.lk/safehaven/1.jpg',     'Rescue operation — Wellawatte Beach'      UNION ALL
    SELECT 'Paws & Claws Sanctuary',                    'https://gallery.pawlink.lk/pawsclaws/1.jpg',     'Seaside sanctuary grounds — Negombo'      UNION ALL
    SELECT 'Galle Animal Welfare Society',              'https://gallery.pawlink.lk/galle/1.jpg',         'Volunteers at Galle Fort cleanup drive'
) g ON o.name = g.org_name;

-- ================================================================
-- 6. ANIMALS
-- ================================================================
-- Descriptions use only breed, location, and condition — no animal names.
-- Each animal is identified throughout the file by a unique description fragment.

-- A1: Nimal's adoption post — Labrador Mix dog (Viharamahadevi Park)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'dog', 'Labrador Mix', '~3 years', 'male', 'Vaccinated, neutered, healthy',
    'low', 6.9157, 79.8636, 'Colombo',
    'A calm and gentle Labrador Mix found near Viharamahadevi Park, Colombo. Gets along well with children and other animals. Vaccinated and neutered. Looking for a loving permanent home.',
    'available', id
FROM users WHERE email = 'nimal@pawlink.com';

-- A2: Nimal's adoption post — Domestic Shorthair cat (Maradana)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'cat', 'Domestic Shorthair', '8 months', 'female', 'Vaccinated, spayed, healthy',
    'low', 6.9022, 79.8553, 'Colombo',
    'A young female Domestic Shorthair rescued from the Maradana railway area. Playful, litter trained, and in good health. Ready for adoption into a caring household.',
    'available', id
FROM users WHERE email = 'nimal@pawlink.com';

-- A3: Nimal's rescue post — Mixed Breed injured dog (Dehiwala)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'dog', 'Mixed Breed', '~1 year', 'unknown', 'Injured right hind leg, needs urgent vet care',
    'critical', 6.8649, 79.8997, 'Dehiwala',
    'A Mixed Breed dog found near Dehiwala junction with a severely injured hind leg. Likely hit by a vehicle. Needs immediate rescue and veterinary attention.',
    'available', id
FROM users WHERE email = 'nimal@pawlink.com';

-- A4: Nimal's rescue post — Persian Mix malnourished cat (Kandy Lake)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'cat', 'Persian Mix', '~2 years', 'female', 'Malnourished, minor skin infection',
    'high', 7.2906, 80.6337, 'Kandy',
    'A Persian Mix cat spotted near Kandy Lake. Very weak and malnourished with a minor skin infection. Could be a lost pet. Needs a foster or rescue organisation urgently.',
    'available', id
FROM users WHERE email = 'nimal@pawlink.com';

-- A5: Nimal's handover post — Dutch Rabbit (Colombo, owner relocating)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'other', 'Dutch Rabbit', '1 year', 'male', 'Healthy, cage-trained',
    'medium', 6.9271, 79.8612, 'Colombo',
    'A domestic Dutch Rabbit whose owner is relocating abroad and cannot take him along. Healthy, cage-trained, and well-fed. Seeking adoption or shelter placement in Colombo.',
    'available', id
FROM users WHERE email = 'nimal@pawlink.com';

-- A6: Kumari — Siamese Mix cat (Peradeniya)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'cat', 'Siamese Mix', '~4 years', 'male', 'Healthy, vaccinated',
    'low', 7.2556, 80.5921, 'Kandy',
    'An affectionate Siamese Mix found near Peradeniya Botanical Gardens. Very social, prefers indoor living. Vaccinated and in good condition.',
    'available', id
FROM users WHERE email = 'kumari@pawlink.com';

-- A7: Suresh — German Shepherd Mix (Mount Lavinia, owner selling property)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'dog', 'German Shepherd Mix', '~5 years', 'male', 'Healthy, good with commands',
    'low', 6.8219, 79.8985, 'Mount Lavinia',
    'A well-trained German Shepherd Mix from Mount Lavinia. Previously a guard dog — owner is selling the property and cannot keep him. Responds to basic commands. Needs urgent adoption.',
    'available', id
FROM users WHERE email = 'suresh@pawlink.com';

-- A8: Dilani — Mixed Breed puppy with injured paw (Galle)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by)
SELECT 'dog', 'Mixed Breed', '~6 months', 'female', 'Injured front paw, otherwise healthy',
    'high', 6.0367, 80.2169, 'Galle',
    'A young Mixed Breed puppy found limping near Galle Bus Stand with an injured front paw. Needs veterinary care and a foster home in the Galle area.',
    'available', id
FROM users WHERE email = 'dilani@pawlink.com';

-- A9: Ruwan — Domestic Longhair cat (Negombo fish market, shelter intake)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by, organization_id)
SELECT 'cat', 'Domestic Longhair', '3 years', 'female', 'Recovering from respiratory infection',
    'medium', 7.2089, 79.8351, 'Negombo',
    'A Domestic Longhair cat brought in from the Negombo fish market area. Recovering well under veterinary care at Paws & Claws Sanctuary. Available for adoption once medically cleared.',
    'available', u.id, o.id
FROM users u, organizations o
WHERE u.email = 'ruwan@pawlink.com' AND o.name = 'Paws & Claws Sanctuary';

-- A10: Shelter intake — Beagle Mix surrendered by owner (Colombo)
INSERT INTO animals
    (type, breed, age, gender, health_condition, rescue_urgency, latitude, longitude, city, description, status, posted_by, organization_id)
SELECT 'dog', 'Beagle Mix', '~2 years', 'male', 'Healthy, vaccinated, neutered',
    'low', 6.9271, 79.8612, 'Colombo',
    'A friendly Beagle Mix surrendered by a family who relocated to an apartment in Colombo. House-trained, vaccinated, and neutered. Loves walks and open spaces.',
    'available', u.id, o.id
FROM users u, organizations o
WHERE u.email = 'shelter@pawlink.com' AND o.name = 'Happy Paws Rescue Foundation';

-- ================================================================
-- 7. ANIMAL IMAGES
-- ================================================================
INSERT INTO animal_images (animal_id, image_url)
SELECT a.id, i.image_url
FROM animals a
JOIN (
    SELECT 'Labrador Mix found near Viharamahadevi Park'     AS desc_fragment, 'https://img.pawlink.lk/animals/labrador_vihara1.jpg'  UNION ALL
    SELECT 'Labrador Mix found near Viharamahadevi Park',                       'https://img.pawlink.lk/animals/labrador_vihara2.jpg'  UNION ALL
    SELECT 'Domestic Shorthair rescued from the Maradana',                      'https://img.pawlink.lk/animals/shorthair_maradana.jpg' UNION ALL
    SELECT 'Mixed Breed dog found near Dehiwala junction',                      'https://img.pawlink.lk/animals/mixed_dehiwala.jpg'    UNION ALL
    SELECT 'Persian Mix cat spotted near Kandy Lake',                           'https://img.pawlink.lk/animals/persian_kandy.jpg'     UNION ALL
    SELECT 'domestic Dutch Rabbit whose owner is relocating',                   'https://img.pawlink.lk/animals/dutch_rabbit.jpg'      UNION ALL
    SELECT 'Siamese Mix found near Peradeniya',                                 'https://img.pawlink.lk/animals/siamese_peradeniya.jpg' UNION ALL
    SELECT 'German Shepherd Mix from Mount Lavinia',                            'https://img.pawlink.lk/animals/shepherd_mtlavinia.jpg' UNION ALL
    SELECT 'Mixed Breed puppy found limping near Galle Bus Stand',              'https://img.pawlink.lk/animals/mixed_galle.jpg'       UNION ALL
    SELECT 'Domestic Longhair cat brought in from the Negombo',                 'https://img.pawlink.lk/animals/longhair_negombo.jpg'  UNION ALL
    SELECT 'Beagle Mix surrendered by a family who relocated',                  'https://img.pawlink.lk/animals/beagle_colombo1.jpg'   UNION ALL
    SELECT 'Beagle Mix surrendered by a family who relocated',                  'https://img.pawlink.lk/animals/beagle_colombo2.jpg'
) i ON a.description LIKE CONCAT('%', i.desc_fragment, '%');

-- ================================================================
-- 8. ADOPTION REQUESTS
-- ================================================================
INSERT INTO adoption_requests (animal_id, requester_id, message, status)
-- Kumari wants to adopt the Labrador Mix (Nimal's dog)
SELECT a.id, u.id,
    'I have a large garden in Kandy and would love to give this Labrador Mix a permanent home. I have experience with dogs.', 'pending'
FROM animals a, users u
WHERE a.description LIKE '%Labrador Mix found near Viharamahadevi%' AND u.email = 'kumari@pawlink.com'
UNION ALL
-- Suresh wants to adopt the Domestic Shorthair (Nimal's cat)
SELECT a.id, u.id,
    'My family has been looking for a friendly cat. This Domestic Shorthair sounds perfect — we have a calm household.', 'approved'
FROM animals a, users u
WHERE a.description LIKE '%Domestic Shorthair rescued from the Maradana%' AND u.email = 'suresh@pawlink.com'
UNION ALL
-- Dilani wants to adopt the Siamese Mix (Kumari's cat)
SELECT a.id, u.id,
    'I live in a quiet home in Galle and would love to adopt this Siamese Mix. I have fostered cats before.', 'pending'
FROM animals a, users u
WHERE a.description LIKE '%Siamese Mix found near Peradeniya%' AND u.email = 'dilani@pawlink.com'
UNION ALL
-- Ruwan wants to adopt the German Shepherd Mix (Suresh's dog)
SELECT a.id, u.id,
    'As a retired vet nurse I can provide this German Shepherd Mix with the care and exercise he needs. I have a secured yard.', 'pending'
FROM animals a, users u
WHERE a.description LIKE '%German Shepherd Mix from Mount Lavinia%' AND u.email = 'ruwan@pawlink.com'
UNION ALL
-- Nimal wants to adopt the Beagle Mix (shelter dog)
SELECT a.id, u.id,
    'I have been following this Beagle Mix on PawLink for a while. I am ready to give him a permanent home in Colombo.', 'approved'
FROM animals a, users u
WHERE a.description LIKE '%Beagle Mix surrendered by a family who relocated%' AND u.email = 'nimal@pawlink.com';

-- ================================================================
-- 9. RESCUE REQUESTS
-- ================================================================
INSERT INTO rescue_requests (animal_id, reported_by, notes, status)
-- Nimal reports the Dehiwala injured Mixed Breed dog
SELECT a.id, u.id,
    'Mixed Breed dog spotted near Dehiwala junction at 8 AM. Lying beside the road, whimpering. Needs pickup urgently.', 'pending'
FROM animals a, users u
WHERE a.description LIKE '%Mixed Breed dog found near Dehiwala junction%' AND u.email = 'nimal@pawlink.com'
UNION ALL
-- Nimal reports the Kandy Persian Mix malnourished cat
SELECT a.id, u.id,
    'Persian Mix cat near Kandy Lake — very weak and barely moving. Could be dehydrated. Needs rescue team today.', 'in_progress'
FROM animals a, users u
WHERE a.description LIKE '%Persian Mix cat spotted near Kandy Lake%' AND u.email = 'nimal@pawlink.com'
UNION ALL
-- Kumari reports injured Galle Mixed Breed puppy
SELECT a.id, u.id,
    'Mixed Breed puppy limping badly near Galle Bus Stand. Multiple passersby noticed. Needs immediate pickup.', 'pending'
FROM animals a, users u
WHERE a.description LIKE '%Mixed Breed puppy found limping near Galle Bus Stand%' AND u.email = 'kumari@pawlink.com'
UNION ALL
-- Suresh reports German Shepherd Mix in Mount Lavinia
SELECT a.id, u.id,
    'Spotted a German Shepherd Mix wandering on the beach road near Mount Lavinia with visible wounds on its back.', 'resolved'
FROM animals a, users u
WHERE a.description LIKE '%German Shepherd Mix from Mount Lavinia%' AND u.email = 'suresh@pawlink.com'
UNION ALL
-- Dilani reports the Domestic Longhair cat in Negombo
SELECT a.id, u.id,
    'Domestic Longhair cat seen near Negombo fish market, clearly ill and sneezing constantly. Seems to have been there for days.', 'in_progress'
FROM animals a, users u
WHERE a.description LIKE '%Domestic Longhair cat brought in from the Negombo%' AND u.email = 'dilani@pawlink.com';

-- ================================================================
-- 10. HANDOVER REQUESTS
-- ================================================================
INSERT INTO handover_requests
    (user_id, organization_id, animal_id, description, pickup_address, animal_type, status, org_notes)
-- Nimal hands over the Dutch Rabbit to Happy Paws
SELECT u.id, o.id, a.id,
    'I have a healthy Dutch Rabbit that I can no longer keep as I am relocating abroad. He is gentle and cage-trained.',
    '45/2 Thurstan Road, Colombo 03', 'other', 'accepted',
    'Will arrange pickup on Saturday morning. Cage and food included.'
FROM users u, organizations o, animals a
WHERE u.email = 'nimal@pawlink.com'
  AND o.name = 'Happy Paws Rescue Foundation'
  AND a.description LIKE '%domestic Dutch Rabbit whose owner is relocating%'
UNION ALL
-- Kumari hands over an injured bird to Animal Lovers Shelter
SELECT u.id, o.id, NULL,
    'Found an injured bird near Peradeniya campus. Need an organisation to take it in. Cannot keep it at home.',
    'Peradeniya University Road, Kandy', 'bird', 'pending', NULL
FROM users u, organizations o
WHERE u.email = 'kumari@pawlink.com' AND o.name = 'Animal Lovers Shelter'
UNION ALL
-- Suresh hands over German Shepherd Mix to Safe Haven
SELECT u.id, o.id, a.id,
    'This German Shepherd Mix needs a shelter as I am moving abroad. He is trained, vaccinated and very loyal.',
    '22 Station Road, Mount Lavinia', 'dog', 'completed',
    'Received the German Shepherd Mix on 15 May. Doing well at the shelter.'
FROM users u, organizations o, animals a
WHERE u.email = 'suresh@pawlink.com'
  AND o.name = 'Safe Haven Rescues'
  AND a.description LIKE '%German Shepherd Mix from Mount Lavinia%'
UNION ALL
-- Dilani hands over Galle Mixed Breed puppy to Galle Animal Welfare
SELECT u.id, o.id, a.id,
    'Found this Mixed Breed puppy with an injured paw near Galle Bus Stand. Cannot foster her due to apartment rules.',
    'Galle Bus Stand, Galle', 'dog', 'accepted', 'Vet visit scheduled for Monday.'
FROM users u, organizations o, animals a
WHERE u.email = 'dilani@pawlink.com'
  AND o.name = 'Galle Animal Welfare Society'
  AND a.description LIKE '%Mixed Breed puppy found limping near Galle Bus Stand%'
UNION ALL
-- Ruwan hands over Domestic Longhair cat to Paws & Claws
SELECT u.id, o.id, a.id,
    'This Domestic Longhair cat needs medical care beyond what I can provide at home. Requesting shelter intake.',
    'Negombo Fish Market, Negombo', 'cat', 'completed',
    'Cat admitted and receiving treatment for respiratory infection.'
FROM users u, organizations o, animals a
WHERE u.email = 'ruwan@pawlink.com'
  AND o.name = 'Paws & Claws Sanctuary'
  AND a.description LIKE '%Domestic Longhair cat brought in from the Negombo%';

-- ================================================================
-- 11. MESSAGES
-- ================================================================
INSERT INTO messages (sender_id, receiver_id, subject, body)
SELECT s.id, r.id, q.sub, q.body
FROM (
    SELECT 'nimal@pawlink.com'     AS sender, 'shelter@pawlink.com'      AS receiver,
        'Inquiry about the Beagle Mix'                                    AS sub,
        'Hello, I submitted an adoption request for the Beagle Mix. Could you let me know the next steps?' AS body
    UNION ALL
    SELECT 'shelter@pawlink.com',  'nimal@pawlink.com',
        'Re: Inquiry about the Beagle Mix',
        'Hi Nimal, thank you for your interest! We have approved your request. Please visit us on Saturday at 10 AM with your NIC.'
    UNION ALL
    SELECT 'kumari@pawlink.com',   'nimal@pawlink.com',
        'About the Labrador Mix at Viharamahadevi',
        'Hi Nimal, I am very interested in the Labrador Mix you posted. I have a large garden in Kandy. Is he still available? What is his temperament like with strangers?'
    UNION ALL
    SELECT 'nimal@pawlink.com',    'kumari@pawlink.com',
        'Re: About the Labrador Mix at Viharamahadevi',
        'Hi Kumari, yes he is still available. Very gentle and good with new people. Would you like to schedule a meet-up?'
    UNION ALL
    SELECT 'dilani@pawlink.com',   'safehaven@pawlink.com',
        'Rescue Team Needed — Galle Area',
        'Hello, there is an injured Mixed Breed puppy near Galle Bus Stand. Is your team able to respond? I can stay with the animal until help arrives.'
) q
JOIN users s ON s.email = q.sender
JOIN users r ON r.email = q.receiver;

-- ================================================================
-- 12. NOTIFICATIONS
-- ================================================================
INSERT INTO notifications (user_id, type, message, is_read, related_id)
-- Notify Nimal about Beagle Mix adoption approval
SELECT u.id, 'adoption_approved',
    'Your adoption request for the Beagle Mix has been approved by Happy Paws Rescue Foundation!', 0, ar.id
FROM users u, adoption_requests ar, animals a
WHERE u.email = 'nimal@pawlink.com'
  AND a.description LIKE '%Beagle Mix surrendered by a family who relocated%'
  AND ar.animal_id = a.id AND ar.requester_id = u.id
UNION ALL
-- Notify Suresh about Domestic Shorthair adoption approval
SELECT u.id, 'adoption_approved',
    'Your adoption request for the Domestic Shorthair has been approved. Please contact the poster to arrange pickup.', 0, ar.id
FROM users u, adoption_requests ar, animals a
WHERE u.email = 'suresh@pawlink.com'
  AND a.description LIKE '%Domestic Shorthair rescued from the Maradana%'
  AND ar.animal_id = a.id AND ar.requester_id = u.id
UNION ALL
-- Notify Nimal that Kumari messaged about the Labrador Mix
SELECT u.id, 'new_message',
    'You have a new message from Kumari Jayasinghe about the Labrador Mix listing.', 0, NULL
FROM users u WHERE u.email = 'nimal@pawlink.com'
UNION ALL
-- Notify shelter about Nimal's new adoption request
SELECT u.id, 'new_adoption_request',
    'A new adoption request has been submitted for the Beagle Mix by Nimal Perera.', 1, NULL
FROM users u WHERE u.email = 'shelter@pawlink.com'
UNION ALL
-- Notify Dilani about rescue status update for Galle puppy
SELECT u.id, 'rescue_update',
    'The rescue request for the Mixed Breed puppy in Galle is now in progress. A team has been assigned.', 0, NULL
FROM users u WHERE u.email = 'dilani@pawlink.com';

-- ================================================================
-- 13. REPORTS (reported BY NIMAL and others)
-- ================================================================
INSERT INTO reports (reporter_id, animal_id, reason, details, status)
-- Nimal reports a suspicious Siamese Mix listing
SELECT u.id, a.id,
    'Suspected fake listing',
    'This Siamese Mix listing appears to use stock photos. The description seems copy-pasted from another platform.',
    'pending'
FROM users u, animals a
WHERE u.email = 'nimal@pawlink.com' AND a.description LIKE '%Siamese Mix found near Peradeniya%'
UNION ALL
-- Nimal reports animal cruelty concern on Dehiwala dog listing
SELECT u.id, a.id,
    'Signs of abuse',
    'The Mixed Breed dog in this listing has visible scars that look intentional. The poster has not responded to any messages.',
    'reviewed'
FROM users u, animals a
WHERE u.email = 'nimal@pawlink.com' AND a.description LIKE '%Mixed Breed dog found near Dehiwala junction%'
UNION ALL
-- Kumari reports misleading health info on German Shepherd Mix
SELECT u.id, a.id,
    'Misleading health information',
    'The German Shepherd Mix listing claims the dog is fully healthy but a vet comment suggests otherwise. Please verify.',
    'pending'
FROM users u, animals a
WHERE u.email = 'kumari@pawlink.com' AND a.description LIKE '%German Shepherd Mix from Mount Lavinia%'
UNION ALL
-- Suresh reports duplicate listing for the Domestic Shorthair
SELECT u.id, a.id,
    'Duplicate listing',
    'This Domestic Shorthair appears in at least two other listings by the same user. Possible spam or double-posting.',
    'dismissed'
FROM users u, animals a
WHERE u.email = 'suresh@pawlink.com' AND a.description LIKE '%Domestic Shorthair rescued from the Maradana%'
UNION ALL
-- Dilani reports welfare concern on Dutch Rabbit listing
SELECT u.id, a.id,
    'Animal welfare concern',
    'The photo in the Dutch Rabbit listing shows the animal in a very small enclosure. Possible welfare concern.',
    'pending'
FROM users u, animals a
WHERE u.email = 'dilani@pawlink.com' AND a.description LIKE '%domestic Dutch Rabbit whose owner is relocating%';

-- ================================================================
-- 14. MEDICAL RECORDS
-- ================================================================
INSERT INTO medical_records (animal_id, recorded_by, record_type, description, record_date)
SELECT a.id, u.id, r.record_type, r.description, r.record_date
FROM animals a, users u,
(
    SELECT 'Beagle Mix surrendered by a family who relocated'    AS desc_fragment,
           'shelter@pawlink.com'                                 AS recorder,
           'Vaccination'                                         AS record_type,
           'Administered DHPP and rabies vaccines on intake. Animal in good health.' AS description,
           CURDATE() - INTERVAL 60 DAY                          AS record_date
    UNION ALL
    SELECT 'Beagle Mix surrendered by a family who relocated',
           'shelter@pawlink.com',
           'Neutering',
           'Neutering procedure completed successfully. No complications.',
           CURDATE() - INTERVAL 30 DAY
    UNION ALL
    SELECT 'Domestic Longhair cat brought in from the Negombo',
           'ruwan@pawlink.com',
           'Treatment',
           'Started 7-day course of doxycycline for upper respiratory tract infection.',
           CURDATE() - INTERVAL 14 DAY
    UNION ALL
    SELECT 'Domestic Longhair cat brought in from the Negombo',
           'ruwan@pawlink.com',
           'Check-up',
           'Respiratory infection clearing well. Weight up 200g since admission. Continuing treatment.',
           CURDATE() - INTERVAL 7 DAY
    UNION ALL
    SELECT 'Labrador Mix found near Viharamahadevi Park',
           'nimal@pawlink.com',
           'Vaccination',
           'Rabies booster and deworming administered by Dr. Wijesekara, Colombo 05.',
           CURDATE() - INTERVAL 45 DAY
    UNION ALL
    SELECT 'Mixed Breed dog found near Dehiwala junction',
           'nimal@pawlink.com',
           'Emergency Treatment',
           'X-ray confirmed hairline fracture in right hind leg. Leg splinted and prescribed rest for 4 weeks.',
           CURDATE() - INTERVAL 5 DAY
) r
WHERE a.description LIKE CONCAT('%', r.desc_fragment, '%')
  AND u.email = r.recorder;

-- ================================================================
-- END OF SEED DATA
-- ================================================================